title: OKD8811
description: >- 
baseurl: "/jekyll_OKD"
url: "http://OKD8811.github.io"

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - github-pages
  - jekyll-feed
  - jekyll-org
  
permalink: /:categories/:short_year-:month-:day/:title

sass:
  sass_dir: _sass
  style: compressed
